//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Budget')
export class BudgetEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  type: string;
}
