//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Project')
export class ProjectEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  projectId: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('text', { nullable: true })
  typeOfTheProject: string;

  @Column('real', { nullable: true })
  budget: number;
}
