//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Project: [
      {
        projectId: 1,
        name: 'Solar Panel Installation',
        typeOfTheProject: 'PRJ',
        budget: 120000.5,
      },
      {
        projectId: 2,
        name: 'Factory Modernization',
        typeOfTheProject: 'MEV',
        budget: 85000,
      },
      {
        projectId: 3,
        name: 'Maintenance Overhaul',
        typeOfTheProject: 'MCO',
        budget: 45000.75,
      },
      {
        projectId: 4,
        name: 'IT Infrastructure Upgrade',
        typeOfTheProject: 'PRJ',
        budget: 99000,
      },
      {
        projectId: 5,
        name: 'Energy Efficiency Program',
        typeOfTheProject: 'MEV',
        budget: 67000.25,
      },
    ],
    Budget: [
      { type: 'Operational' },
      { type: 'Capital' },
      { type: 'Research' },
      { type: 'Maintenance' },
      { type: 'Development' },
    ],
    Year: [
      { year: 2024 },
      { year: 2025 },
      { year: 2026 },
      { year: 2027 },
      { year: 2028 },
    ],
    User: [
      { name: 'Alice', surname: 'Dupont' },
      { name: 'Mohamed', surname: 'Benali' },
      { name: 'Sophie', surname: 'Martin' },
      { name: 'Lucas', surname: 'Moreau' },
      { name: 'Fatima', surname: 'El Amrani' },
    ],
  },
};
export default data;
